FROM php:8.1-fpm

RUN set -eux \
	&& DEBIAN_FRONTEND=noninteractive apt-get update -qq \
	&& DEBIAN_FRONTEND=noninteractive apt-get install -qq -y --no-install-recommends --no-install-suggests \
		ca-certificates \
		gettext-base \
		git \
		iproute2 \
		iputils-ping \
		libzip-dev \
		unzip \
		zip \
		zlib1g-dev \
	&& rm -rf /var/lib/apt/lists/*

RUN set -eux \
	&& docker-php-ext-install -j$(getconf _NPROCESSORS_ONLN) sockets pdo_mysql zip

RUN set -eux \
	&& pecl install xdebug-3.4.4 \
	&& docker-php-ext-enable xdebug

ENV COMPOSER_ALLOW_SUPERUSER 1
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
ADD composer/auth.json /root/.composer/auth.json
RUN git config --global --add safe.directory /var/www/app

RUN mv $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini
ADD php-local.ini /usr/local/etc/php/conf.d/zzz-custom.ini

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint
COPY docker-entrypoint-local.sh /usr/local/bin/docker-entrypoint-local
RUN chmod +x /usr/local/bin/docker-entrypoint /usr/local/bin/docker-entrypoint-local
ENTRYPOINT ["/usr/local/bin/docker-entrypoint", "/usr/local/bin/docker-entrypoint-local"]

WORKDIR /var/www/app

CMD ["php-fpm"]
