services:
  mysql:
    container_name: service-marketplace-mysql
    image: mysql:8.4
    volumes:
      - ./var/mysql:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_MYSQL_ROOT_PASS}
      MYSQL_DATABASE: ${APP_MYSQL_DB}
      MYSQL_PASSWORD: ${APP_MYSQL_PASS}
      MYSQL_USER: ${APP_MYSQL_USER}
    restart: always
  nginx:
    build: ./docker/nginx
    container_name: service-marketplace-nginx
    env_file: .env
    depends_on:
      - php
    ports:
      - "${APP_HTTP_PORT}:${APP_HTTP_PORT}"
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
      - ./var/log/nginx:/var/log/nginx
      - ./:/var/www/app
    restart: always
  php:
    build:
      context: ./docker/php
    env_file: .env
    container_name: service-marketplace-php
    depends_on:
      - mysql
    volumes:
      - ./:/var/www/app
    restart: always
